### ISSUE TITLE
Make site work without cgi.fcgi thing

### ISSUE THREAD

**Issue by MichelleGlauser** [MichelleGlauser/techtonica#37]
/cgi.fcgi/ makes its way into the URLs. Please figure out a different solution. ![screen shot 2017-01-20 at 4 57 21 pm](https://cloud.githubusercontent.com/assets/1952773/22170379/99bc4426-df31-11e6-96dc-41281ad8210c.png)

**Comment by heyellieday** [comment]
Based on my initial research, this issue could be solved by setting proper config values as described here: http://flask.pocoo.org/docs/0.12/config/

This assumption is based on fact that both the urls [with](http://techtonica.org/cgi.fcgi/about/) and [without](http://techtonica.org/about/) "cgi.fcgi" are able to be served to the client. From my understanding, the "cgi.fcgi" url fragment is introduced by the "url_for" helper method:

`<a href="{{ url_for('render_about_page') }}" class="aboutus nav-link">About</a>`

If the `SERVER_NAME` value was properly set, then there is a good chance this would not happen, as url_for generates the "base url" from that value. However, since I am unable to reproduce the "cgi.fcgi" isssue locally, I am not entirely sure.

**Comment by MichelleGlauser** [comment]
I'm not sure it's the "url_for" helper, because when you go directly to a page, the address still changes to include "cgi.fcgi." I can certainly try the SERVER_NAME thing. What were you thinking it should be set to, @heyellieday?

**Comment by murphdasmurf** [comment]
It was actually just an Apache configuration issue. Fixed it in cpanel via the text editor.
