### ISSUE TITLE
Fix spacing around contact us button on /conduct page.

### ISSUE THREAD

**Issue by MichelleGlauser** [MichelleGlauser/techtonica#99]
The contact us button on [the Code of Conduct page](https://techtonica.org/conduct/) could use some improved spacing.

**Comment by hnarasaki** [comment]
@MichelleGlauser How would you like the button to look ideally? Would you like it to look more centered kind of like on https://techtonica.org/sponsor/? I also noticed the Contact button on https://techtonica.org/team/ & https://techtonica.org/openings/.

**Comment by hnarasaki** [comment]
I followed the setup on https://github.com/MichelleGlauser/techtonica, but when I navigate to https://github.com/MichelleGlauser/techtonica, I get a Key Error. In PyCharm, if I debug main_site.py, I receive this in terminal "/usr/local/bin/python3.7 "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 51548 --file /Users/hnarasaki/dev/techtonica/main_site.py
pydev debugger: process 31808 is connecting

Connected to pydev debugger (build 191.7479.30)
/usr/local/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.2) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1758, in <module>
    main()
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/hnarasaki/dev/techtonica/main_site.py", line 17, in <module>
    EVENTBRITE_OAUTH_TOKEN = os.environ["EVENTBRITE_OAUTH_TOKEN"]
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'EVENTBRITE_OAUTH_TOKEN'

Process finished with exit code 1"
I tried to downgrade urllib3 to a lower version, but still get the same error. Have you seen this come up before?
Do any new setup steps need to be added to the Readme due to new changes in "requirements.in	Load Eventbrite token from .env	3 months ago"?

<img width="1665" alt="Screen Shot 2019-06-27 at 4 55 32 PM" src="https://user-images.githubusercontent.com/29487319/60308154-6bd7dc00-98fc-11e9-8506-bfeffbb26900.png">

**Comment by KGmajor** [comment]
Resolved on another PR
